# Generated by Django 4.2.4 on 2023-09-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useruploadeditem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadeditem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
