# Generated by Django 4.2.4 on 2023-09-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_useruploadeditem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploadeditem',
            name='quantity',
        ),
    ]
