# Generated by Django 4.2.4 on 2023-09-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_calc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='calc',
        ),
    ]
