# Generated by Django 4.2.4 on 2023-09-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default='none', upload_to='cartImage/'),
        ),
    ]
