# Generated by Django 4.2.4 on 2023-09-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cart_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
