# Generated by Django 4.2.4 on 2023-09-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(upload_to='cartImage/'),
        ),
    ]
