# Generated by Django 4.2.4 on 2023-09-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(upload_to='cart/'),
        ),
    ]
