# Generated by Django 4.2.4 on 2023-09-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cart_item_id_alter_cart_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
